trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@4
  displayName: 'Build Maven Project'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    publishJUnitResults: false

- script: |
    echo "Files in target folder:"
    ls -la target
  displayName: 'Verify build output'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'azureConnectionYaml'
    appType: 'webAppLinux'
    appName: 'yamlPipelineApp'
    package: '$(System.DefaultWorkingDirectory)/target/*.jar'