trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'azureConnectionYaml'
  webAppName: 'yamlPipelineApp'

steps:
- task: Maven@4
  displayName: 'Build Maven Project'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    publishJUnitResults: false

- task: CopyFiles@2
  displayName: 'Copy JAR'
  inputs:
    Contents: 'target/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'azureConnectionYaml'
    appType: 'webAppLinux'
    appName: 'yamlPipelineApp'
    package: '$(Build.ArtifactStagingDirectory)/*.jar'