trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@4
  displayName: 'Build Maven Project'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    publishJUnitResults: false

- task: CopyFiles@2
  displayName: 'Copy JAR'
  inputs:
    Contents: 'target/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    echo "Files in target folder:"
    ls -la target
    echo "Files in artifact staging folder:"
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'Verify JAR files'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'azureConnectionYaml'
    appType: 'webAppLinux'
    appName: 'yamlPipelineApp'
    package: '$(Build.ArtifactStagingDirectory)/*.jar'